import "./globals.css";
import Navbar from "@/components/navbar";
import GlowCursor from "@/components/GlowCursor";

export const metadata = {
  title: "Ibrahim ANIL ~ Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className="relative bg-black text-white">
        <GlowCursor />
        <Navbar />
        <main className="p-20">{children}</main>
      </body>
    </html>
  );
}