import "./globals.css";
import Navbar from "@/components/navbar";

export const metadata = {
  title: "Ibrahim ANIL ~ Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body
        className="p-20"
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}