import "./globals.css";
import Navbar from "@/components/navbar";
import GlowCursor from "@/components/GlowCursor";
import { ViewTransitions } from "next-view-transitions";

export const metadata = {
  title: "Ibrahim ANIL ~ Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html lang="fr">
        <body className="relative bg-black text-white overflow-hidden">
          <GlowCursor />
          <Navbar />
          {children}
        </body>
      </html>
    </ViewTransitions>
  ); 
}